// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma CLI（migrate deploy / seed 等）用の接続。
    // 本番はNeonの direct 接続を DATABASE_URL_DIRECT に設定する
    // （pooled(-pooler)接続はpgbouncer経由でDDLに不向きなため）。
    // 未設定ならローカル同様 DATABASE_URL を使う。アプリ実行時は src/lib/db.ts（pooled）。
    url: process.env["DATABASE_URL_DIRECT"] ?? process.env["DATABASE_URL"],
  },
});
