// おかいもの（SHOP.cat）のTSマスタ（ダンジョン/げんばと同方針: DBに持たずID参照）。
// クライアントからも読まれるので prisma 依存禁止。通貨はEN（げんばで稼ぐ）。
// 竹版は「マイホームのかざり棚に並ぶ家具・置物」12種から。家の拡張（大物）は次フェーズ。

export type ShopItem = {
  id: string;
  name: string;
  desc: string;
  price: number; // EN
  sprite: string[]; // 12x12 ドット絵（shop-sprite.tsx の色表参照）
};

export const SHOP_ITEMS: ShopItem[] = [
  {
    id: "poster",
    name: "きんのたまごポスター",
    desc: "「初心わするべからず」。転生者に人気の一枚",
    price: 200,
    sprite: [
      "kkkkkkkkkkkk",
      "kwwwwwwwwwwk",
      "kwwwyyyywwwk",
      "kwwyyyyyywwk",
      "kwwyywyyywwk",
      "kwwyyyyyywwk",
      "kwwyyyyyywwk",
      "kwwwyyyywwwk",
      "kwwwwwwwwwwk",
      "kkkkkkkkkkkk",
      "............",
      "............",
    ],
  },
  {
    id: "plant",
    name: "かんようしょくぶつ",
    desc: "現場で荒んだ心に、みどりを",
    price: 300,
    sprite: [
      "............",
      "....gg......",
      "..gggggg.g..",
      ".gggggggggg.",
      "..gggggggg..",
      "...gggggg...",
      "....gggg....",
      "....nnnn....",
      "...nnnnnn...",
      "...nnnnnn...",
      "....nnnn....",
      "............",
    ],
  },
  {
    id: "lamp",
    name: "フロアランプ",
    desc: "夜のコーディングを、あたたかく照らす",
    price: 400,
    sprite: [
      "...yyyyyy...",
      "..yyyyyyyy..",
      ".yyyyyyyyyy.",
      ".yyyyyyyyyy.",
      "..yyyyyyyy..",
      ".....kk.....",
      ".....kk.....",
      ".....kk.....",
      ".....kk.....",
      ".....kk.....",
      "...kkkkkk...",
      "............",
    ],
  },
  {
    id: "rug",
    name: "ふわふわラグ",
    desc: "ペットがまっさきに寝転ぶ場所",
    price: 500,
    sprite: [
      "............",
      "............",
      "............",
      "............",
      "............",
      "............",
      "...pppppp...",
      ".pppwwwwppp.",
      "ppwwppppwwpp",
      ".pppwwwwppp.",
      "...pppppp...",
      "............",
    ],
  },
  {
    id: "coffee",
    name: "コーヒーメーカー",
    desc: "朝会前の一杯が現場の平和を守る",
    price: 600,
    sprite: [
      "............",
      "..kkkkkkkk..",
      "..knnnnnnk..",
      "..kkkkkkkk..",
      "..kk....kk..",
      "..kkwwwwkk..",
      "..kkwnnwkk..",
      "..kkwnnwkk..",
      "..kkwwwwkk..",
      "..kkkkkkkk..",
      "..kkkkkkkk..",
      "............",
    ],
  },
  {
    id: "bookshelf",
    name: "ほんだな",
    desc: "背表紙を眺めるだけで強くなった気がする",
    price: 700,
    sprite: [
      "kkkkkkkkkkkk",
      "knnnnnnnnnnk",
      "knrygbrygbnk",
      "knrygbrygbnk",
      "knnnnnnnnnnk",
      "knbgyrbgyrnk",
      "knbgyrbgyrnk",
      "knnnnnnnnnnk",
      "knygrbygrbnk",
      "knygrbygrbnk",
      "kkkkkkkkkkkk",
      "............",
    ],
  },
  {
    id: "sofa",
    name: "ふかふかソファ",
    desc: "満了明けの休日はここから動かない",
    price: 800,
    sprite: [
      "............",
      "............",
      "............",
      ".rr......rr.",
      ".rrrrrrrrrr.",
      ".rrwwwwwwrr.",
      ".rrwwwwwwrr.",
      ".rrrrrrrrrr.",
      ".rrrrrrrrrr.",
      ".kk......kk.",
      "............",
      "............",
    ],
  },
  {
    id: "cattower",
    name: "キャットタワー",
    desc: "鳥もスライムも、なぜかのぼりたがる",
    price: 900,
    sprite: [
      "..nnnnnn....",
      "..nnnnnn....",
      ".....kk.....",
      "....nnnnnn..",
      "....nnnnnn..",
      ".....kk.....",
      ".....kk.....",
      "..nnnnnnnn..",
      "..nnnnnnnn..",
      ".....kk.....",
      "...kkkkkk...",
      "............",
    ],
  },
  {
    id: "fridge",
    name: "れいぞうこ",
    desc: "ごはんのストックがちょっと誇らしい",
    price: 1000,
    sprite: [
      "..kkkkkkkk..",
      "..kwwwwwwk..",
      "..kwwwwkwk..",
      "..kwwwwwwk..",
      "..kkkkkkkk..",
      "..kwwwwwwk..",
      "..kwwwwkwk..",
      "..kwwwwwwk..",
      "..kwwwwwwk..",
      "..kwwwwwwk..",
      "..kkkkkkkk..",
      "............",
    ],
  },
  {
    id: "aquarium",
    name: "ちいさな水槽",
    desc: "ゆらゆら泳ぐ魚は、レビュー待ちの心の薬",
    price: 1200,
    sprite: [
      "kkkkkkkkkkkk",
      "kssssssssssk",
      "kssssssssssk",
      "kssrrsssssok",
      "ksrrrrssssok",
      "kssrrsssssok",
      "kssssssgsssk",
      "ksssssgggssk",
      "kssgggggssgk",
      "kggssggssggk",
      "kkkkkkkkkkkk",
      "............",
    ],
  },
  {
    id: "tv",
    name: "だいがめんテレビ",
    desc: "リビングの主役。家族会議もゲームもこれで",
    price: 1500,
    sprite: [
      "kkkkkkkkkkkk",
      "kbbbbbbbbbbk",
      "kbbsbbbbbbbk",
      "kbsbbbbbbbbk",
      "kbbbbbbbbbbk",
      "kbbbbbbbbbbk",
      "kbbbbbbbbbbk",
      "kkkkkkkkkkkk",
      ".....kk.....",
      "...kkkkkk...",
      "............",
      "............",
    ],
  },
  {
    id: "trophy",
    name: "満了トロフィー",
    desc: "契約満了の誇り。ハトリさんもうれしそう",
    price: 2000,
    sprite: [
      "............",
      "..yyyyyyyy..",
      "..y.yyyy.y..",
      "..y.yyyy.y..",
      "...yyyyyy...",
      "....yyyy....",
      ".....yy.....",
      ".....yy.....",
      "....yyyy....",
      "...kkkkkk...",
      "..kkkkkkkk..",
      "............",
    ],
  },
];

export const shopItemById = (id: string): ShopItem | undefined =>
  SHOP_ITEMS.find((i) => i.id === id);
